default_language_version:
    python: python3
repos:
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    name: isort
    stages: [pre-commit]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-executables-have-shebangs
  - id: check-json
  - id: check-yaml
    args: [--unsafe]  # allow Python constructors
  - id: check-merge-conflict
  - id: check-symlinks
  - id: mixed-line-ending
  - id: pretty-format-json
    args: [--autofix]

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.8.1
  hooks:
    - id: ruff-format
      types_or: [ python, pyi, jupyter ]
    - id: ruff
      types_or: [ python, pyi, jupyter ]
      args: [ --fix, --unsafe-fixes]
