name: dwind
channels:
  - defaults
  - conda-forge
  - nrel
dependencies:
  - python=3.10
  - pandas=2.1.0
  - numpy=1.25.2
  - sqlalchemy=2.0.20
  - psycopg2=2.9.7
  - scipy=1.11.2
  - nrel-pysam=4.2.0
  - nrel-rex=0.2.84
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - pip=23.2.1
  - pip:
    - h5pyd=0.15.1