location = "colorado_larimer"
sector = "btm"
scenario = "baseline"
incentives = "standard"
year = 2025
#repository = "/glade/u/home/calebp/dwind"
dir_out = "/glade/u/home/calebp/dwind_output"
#nodes = 1
#allocation = "UCSG0003"
#memory = 120  # GB
#walltime = 20  # hrs
#feature = "--qos=normal"
#env = "/glade/work/calebp/conda-envs/dwind"
model_config = "/glade/u/home/calebp/dwind/examples/model_config.toml"
