location = "colorado_larimer"
sector = "btm"
scenario = "baseline"
year = 2025
repository = "/path/to/cloned/dwind"
dir_out = "/path/to/save/logs_and_data"
nodes = 1
allocation = "dwind"
memory = 120  # GB
walltime = 20  # hrs
feature = "--qos=normal"
env = "/path/to/conda/environment/"
model_config = "/path/to/model_configuraiton_file"
